### ISSUE TITLE
Rename handler class

### ISSUE THREAD

**Issue by ol0lll** [thunder/entity_reference_actions#6]
The class should have a different name since it is not a form, maybe EntityActions EntitiyOperations or something along the line.
Also namespace and directory should not include Form, since again its not a form.

https://github.com/thunder/entity_reference_actions/blob/c1316565256444a08c5bfd8f6cb0afbe111b4449/src/Form/ActionForm.php#L3L19

**Comment by chrfritsch** [comment]
EntityReferenceActionsHandler
